# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95fe688a15fa290a02087559a8becb6a81b9806fa870ab6c4ba8e005574ceea4c23233afca116f960defd60beb39bbb4ca57c5aeb4b5c3ea90021f64b3a602d1

test:
  secret_key_base: 1a23c3dcd0af293e58630e8d9aeb96eb718e681371a1125cab5998b044e3f648562c34a1301803d9b8d0768daa7c630ee367ef59a425d36d6557a0c3f17ea9b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
